/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EventosPOOII;

import javax.swing.JOptionPane;

/**
 *
 * @author everson.silva
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoVendaItinerario = new javax.swing.ButtonGroup();
        grupoCancelarPassagem = new javax.swing.ButtonGroup();
        grupoConsultaPassagem = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        vendaViagem = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        campoVendaNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoVendaCPF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoVendaPoltrona = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        campoVendaData = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        radioVendaPTCxUDI = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        radioVendaPTCxPMS = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        botaoVendaCancelar = new javax.swing.JButton();
        botaoVendaApagar = new javax.swing.JButton();
        botaoVendaProsseguir = new javax.swing.JButton();
        consultaViagem = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        radioConsultaPTCxUDI = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        radioConsultaPTCxPMS = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        campoConsultaData = new javax.swing.JFormattedTextField();
        jPanel9 = new javax.swing.JPanel();
        botaoConsultaCancelar = new javax.swing.JButton();
        botaoConsultaApagar = new javax.swing.JButton();
        botaoConsultaProsseguir = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        cancelarViagem = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        botaoCancelamentoCancelar = new javax.swing.JButton();
        botaoCancelamentoApagar = new javax.swing.JButton();
        botaoCancelamentoProsseguir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        campoCancelamentoNome = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        campoCancelamentoPoltrona = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        campoCancelamentoData = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        radioCancelamentoPTCxUDI = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        radioCancelamentoPTCxPMS = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Landing Lines");

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventosPOOII/red-bus.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(253, 98, 98));
        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(253, 98, 98));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LINES");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(253, 98, 98));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LANDING");

        jLabel4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(253, 98, 98));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Venda de Passagens");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.GridLayout(6, 2, 7, 0));

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nome:");
        jPanel1.add(jLabel8);
        jPanel1.add(campoVendaNome);

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("CPF:");
        jPanel1.add(jLabel7);
        jPanel1.add(campoVendaCPF);

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Poltrona:");
        jPanel1.add(jLabel6);
        jPanel1.add(campoVendaPoltrona);

        jLabel15.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Data:");
        jPanel1.add(jLabel15);

        campoVendaData.setColumns(3);
        jPanel1.add(campoVendaData);

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Itinerário 1:");
        jPanel1.add(jLabel11);

        grupoVendaItinerario.add(radioVendaPTCxUDI);
        radioVendaPTCxUDI.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        radioVendaPTCxUDI.setForeground(new java.awt.Color(255, 255, 255));
        radioVendaPTCxUDI.setText("Patrocínio a Uberlândia R$ 50,00");
        jPanel1.add(radioVendaPTCxUDI);

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Itinerário 2:");
        jPanel1.add(jLabel12);

        grupoVendaItinerario.add(radioVendaPTCxPMS);
        radioVendaPTCxPMS.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        radioVendaPTCxPMS.setForeground(new java.awt.Color(255, 255, 255));
        radioVendaPTCxPMS.setText("Patrocínio a Patos de Minas R$ 35,00");
        jPanel1.add(radioVendaPTCxPMS);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 50, 0));

        botaoVendaCancelar.setBackground(new java.awt.Color(204, 204, 204));
        botaoVendaCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventosPOOII/x-red.png"))); // NOI18N
        botaoVendaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVendaCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(botaoVendaCancelar);

        botaoVendaApagar.setBackground(new java.awt.Color(204, 204, 204));
        botaoVendaApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventosPOOII/apagador-red.png"))); // NOI18N
        botaoVendaApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVendaApagarActionPerformed(evt);
            }
        });
        jPanel3.add(botaoVendaApagar);

        botaoVendaProsseguir.setBackground(new java.awt.Color(204, 204, 204));
        botaoVendaProsseguir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventosPOOII/próximo-red.png"))); // NOI18N
        botaoVendaProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVendaProsseguirActionPerformed(evt);
            }
        });
        jPanel3.add(botaoVendaProsseguir);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout vendaViagemLayout = new javax.swing.GroupLayout(vendaViagem);
        vendaViagem.setLayout(vendaViagemLayout);
        vendaViagemLayout.setHorizontalGroup(
            vendaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vendaViagemLayout.setVerticalGroup(
            vendaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Venda de Passagens", vendaViagem);

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new java.awt.GridLayout(3, 3));

        jLabel22.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Itinerario 1:");
        jPanel8.add(jLabel22);

        grupoConsultaPassagem.add(radioConsultaPTCxUDI);
        radioConsultaPTCxUDI.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        radioConsultaPTCxUDI.setForeground(new java.awt.Color(255, 255, 255));
        radioConsultaPTCxUDI.setText("Patrocínio x Uberlândia");
        jPanel8.add(radioConsultaPTCxUDI);

        jLabel23.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Itinerario 2:");
        jPanel8.add(jLabel23);

        grupoConsultaPassagem.add(radioConsultaPTCxPMS);
        radioConsultaPTCxPMS.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        radioConsultaPTCxPMS.setForeground(new java.awt.Color(255, 255, 255));
        radioConsultaPTCxPMS.setText("Patrocínio x Patos de Minas");
        jPanel8.add(radioConsultaPTCxPMS);

        jLabel24.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Data:");
        jPanel8.add(jLabel24);
        jPanel8.add(campoConsultaData);

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(new java.awt.GridLayout(1, 3, 50, 0));

        botaoConsultaCancelar.setBackground(new java.awt.Color(204, 204, 204));
        botaoConsultaCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventosPOOII/x-red.png"))); // NOI18N
        botaoConsultaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultaCancelarActionPerformed(evt);
            }
        });
        jPanel9.add(botaoConsultaCancelar);

        botaoConsultaApagar.setBackground(new java.awt.Color(204, 204, 204));
        botaoConsultaApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventosPOOII/apagador-red.png"))); // NOI18N
        botaoConsultaApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultaApagarActionPerformed(evt);
            }
        });
        jPanel9.add(botaoConsultaApagar);

        botaoConsultaProsseguir.setBackground(new java.awt.Color(204, 204, 204));
        botaoConsultaProsseguir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventosPOOII/próximo-red.png"))); // NOI18N
        botaoConsultaProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultaProsseguirActionPerformed(evt);
            }
        });
        jPanel9.add(botaoConsultaProsseguir);

        jLabel25.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(253, 98, 98));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Consulta de Passagens");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventosPOOII/red-bus.png"))); // NOI18N

        jLabel30.setBackground(new java.awt.Color(51, 51, 51));
        jLabel30.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(253, 98, 98));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("LANDING");

        jLabel31.setBackground(new java.awt.Color(253, 98, 98));
        jLabel31.setFont(new java.awt.Font("Gill Sans MT", 2, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(253, 98, 98));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("LINES");
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel29)))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))))
                .addGap(60, 60, 60))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout consultaViagemLayout = new javax.swing.GroupLayout(consultaViagem);
        consultaViagem.setLayout(consultaViagemLayout);
        consultaViagemLayout.setHorizontalGroup(
            consultaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        consultaViagemLayout.setVerticalGroup(
            consultaViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Consulta de Viagens", consultaViagem);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventosPOOII/red-bus.png"))); // NOI18N

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(253, 98, 98));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("LANDING");

        jLabel14.setBackground(new java.awt.Color(253, 98, 98));
        jLabel14.setFont(new java.awt.Font("Gill Sans MT", 2, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(253, 98, 98));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("LINES");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel16.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(253, 98, 98));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Cancelamento de Passagem");

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new java.awt.GridLayout(1, 3, 50, 0));

        botaoCancelamentoCancelar.setBackground(new java.awt.Color(204, 204, 204));
        botaoCancelamentoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventosPOOII/x-red.png"))); // NOI18N
        botaoCancelamentoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelamentoCancelarActionPerformed(evt);
            }
        });
        jPanel5.add(botaoCancelamentoCancelar);

        botaoCancelamentoApagar.setBackground(new java.awt.Color(204, 204, 204));
        botaoCancelamentoApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventosPOOII/apagador-red.png"))); // NOI18N
        botaoCancelamentoApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelamentoApagarActionPerformed(evt);
            }
        });
        jPanel5.add(botaoCancelamentoApagar);

        botaoCancelamentoProsseguir.setBackground(new java.awt.Color(204, 204, 204));
        botaoCancelamentoProsseguir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventosPOOII/próximo-red.png"))); // NOI18N
        botaoCancelamentoProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelamentoProsseguirActionPerformed(evt);
            }
        });
        jPanel5.add(botaoCancelamentoProsseguir);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new java.awt.GridLayout(5, 2));

        jLabel17.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Nome:");
        jPanel6.add(jLabel17);
        jPanel6.add(campoCancelamentoNome);

        jLabel18.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Poltrona:");
        jPanel6.add(jLabel18);
        jPanel6.add(campoCancelamentoPoltrona);

        jLabel19.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Data:");
        jPanel6.add(jLabel19);
        jPanel6.add(campoCancelamentoData);

        jLabel20.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Itinerario 1:");
        jPanel6.add(jLabel20);

        grupoCancelarPassagem.add(radioCancelamentoPTCxUDI);
        radioCancelamentoPTCxUDI.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        radioCancelamentoPTCxUDI.setForeground(new java.awt.Color(255, 255, 255));
        radioCancelamentoPTCxUDI.setText("Patrocínio x Uberlândia");
        jPanel6.add(radioCancelamentoPTCxUDI);

        jLabel21.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Itinerario 2:");
        jPanel6.add(jLabel21);

        grupoCancelarPassagem.add(radioCancelamentoPTCxPMS);
        radioCancelamentoPTCxPMS.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        radioCancelamentoPTCxPMS.setForeground(new java.awt.Color(255, 255, 255));
        radioCancelamentoPTCxPMS.setText("Patrocínio x Patos de Minas");
        jPanel6.add(radioCancelamentoPTCxPMS);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cancelarViagemLayout = new javax.swing.GroupLayout(cancelarViagem);
        cancelarViagem.setLayout(cancelarViagemLayout);
        cancelarViagemLayout.setHorizontalGroup(
            cancelarViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cancelarViagemLayout.setVerticalGroup(
            cancelarViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cancelamento de Viagens", cancelarViagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Venda de Passagens");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelamentoApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelamentoApagarActionPerformed
        // TODO add your handling code here:
        campoCancelamentoNome.setText("");
        campoCancelamentoData.setText("");
        campoCancelamentoPoltrona.setText("");
        grupoCancelarPassagem.clearSelection();
    }//GEN-LAST:event_botaoCancelamentoApagarActionPerformed

    private void botaoCancelamentoProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelamentoProsseguirActionPerformed
        // TODO add your handling code here:
        String auxNome = campoCancelamentoNome.getText();
        String auxData = campoCancelamentoData.getText();
        String auxPoltrona = campoCancelamentoPoltrona.getText();
        String auxViagem = "Patrocício x Uberlândia";
        if(radioCancelamentoPTCxPMS.isSelected()) {
            auxViagem = "Patrocício x Patos de Minas";
        }
        
        String imprimir = "Nome do passageiro: " + auxNome +
                          "\nData: " + auxData +
                          "\nPoltrona: " + auxPoltrona +
                          "\nItinerario: " + auxViagem;
        
        JOptionPane.showMessageDialog(null, imprimir);
    }//GEN-LAST:event_botaoCancelamentoProsseguirActionPerformed

    private void botaoConsultaApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultaApagarActionPerformed
        // TODO add your handling code here:
        campoConsultaData.setText("");
        grupoConsultaPassagem.clearSelection();
    }//GEN-LAST:event_botaoConsultaApagarActionPerformed

    private void botaoConsultaProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultaProsseguirActionPerformed
        // TODO add your handling code here:
        String auxData = campoConsultaData.getText();
        String auxViagem = "Patrocício x Uberlândia";
        if(radioConsultaPTCxPMS.isSelected()) {
            auxViagem = "Patrocício x Patos de Minas";
        }
        
        String imprimir = "Na data: " + auxData + ", a viagem de " + auxViagem + " tem XX poltronas livres";
        
        JOptionPane.showMessageDialog(null, imprimir);
    }//GEN-LAST:event_botaoConsultaProsseguirActionPerformed

    private void botaoVendaApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVendaApagarActionPerformed
        // TODO add your handling code here:
        campoVendaNome.setText("");
        campoVendaData.setText("");
        campoVendaCPF.setText("");
        campoVendaPoltrona.setText("");
        grupoVendaItinerario.clearSelection();        
    }//GEN-LAST:event_botaoVendaApagarActionPerformed

    private void botaoVendaProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVendaProsseguirActionPerformed
        // TODO add your handling code here:
        String auxNome = campoVendaNome.getText();
        String auxData = campoVendaData.getText();
        String auxCPF = campoVendaCPF.getText();
        String auxPoltrona = campoVendaPoltrona.getText();
        String auxItinerario = "Patrocínio a Uberlândia com o valor de R$50,00";
        if (radioVendaPTCxPMS.isSelected()) {
            auxItinerario = "Patrocinio a Patos de Minas com o valor de R$35,00";
        }
        
        String imprimir = "Nome do Passageiro: " + auxNome + " com o CPF: " + auxCPF +
                          "\nData da Viagem: " + auxData +
                          "\nPoltrona numero: " + auxPoltrona +
                          "\nItinerario: " + auxItinerario;
        
        JOptionPane.showMessageDialog(null, imprimir);
    }//GEN-LAST:event_botaoVendaProsseguirActionPerformed

    private void botaoVendaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVendaCancelarActionPerformed
        // TODO add your handling code here:        
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_botaoVendaCancelarActionPerformed

    private void botaoConsultaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultaCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_botaoConsultaCancelarActionPerformed

    private void botaoCancelamentoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelamentoCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_botaoCancelamentoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelamentoApagar;
    private javax.swing.JButton botaoCancelamentoCancelar;
    private javax.swing.JButton botaoCancelamentoProsseguir;
    private javax.swing.JButton botaoConsultaApagar;
    private javax.swing.JButton botaoConsultaCancelar;
    private javax.swing.JButton botaoConsultaProsseguir;
    private javax.swing.JButton botaoVendaApagar;
    private javax.swing.JButton botaoVendaCancelar;
    private javax.swing.JButton botaoVendaProsseguir;
    private javax.swing.JTextField campoCancelamentoData;
    private javax.swing.JTextField campoCancelamentoNome;
    private javax.swing.JFormattedTextField campoCancelamentoPoltrona;
    private javax.swing.JFormattedTextField campoConsultaData;
    private javax.swing.JTextField campoVendaCPF;
    private javax.swing.JFormattedTextField campoVendaData;
    private javax.swing.JTextField campoVendaNome;
    private javax.swing.JTextField campoVendaPoltrona;
    private javax.swing.JPanel cancelarViagem;
    private javax.swing.JPanel consultaViagem;
    private javax.swing.ButtonGroup grupoCancelarPassagem;
    private javax.swing.ButtonGroup grupoConsultaPassagem;
    private javax.swing.ButtonGroup grupoVendaItinerario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton radioCancelamentoPTCxPMS;
    private javax.swing.JRadioButton radioCancelamentoPTCxUDI;
    private javax.swing.JRadioButton radioConsultaPTCxPMS;
    private javax.swing.JRadioButton radioConsultaPTCxUDI;
    private javax.swing.JRadioButton radioVendaPTCxPMS;
    private javax.swing.JRadioButton radioVendaPTCxUDI;
    private javax.swing.JPanel vendaViagem;
    // End of variables declaration//GEN-END:variables
}
